sources:
  - name: jaffle_shop
    description: source data comes from jaffle shop
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: customers dataset where one row per customer
        # identifier: customer132323444442332
      - name: orders
        description: orders dataset where one row per customer
        config: 
          freshness:
            warn_after:
              count: 12
              period: hour
            error_after:
              count: 24
              period: hour
          loaded_at_field: _etl_loaded_at
        columns:
          - name: id
            description: unique id of the order
            data_tests:
              - not_null
              - unique    
          - name: user_id
            description: unique id of the customer
            data_tests:
              - not_null
              - relationships:
                  to: source('jaffle_shop', 'customers')
                  field: id
          - name: status
            data_tests:
              - accepted_values:
                  values: ['placed', 'return_pending','returned','completed','shipped']